all: Check_Attack Flooding_Attack Launching_Attack run

Check_Attack:
	gcc Check_Attack.c -o Check_Attack
Flooding_Attack:
	gcc Flooding_Attack.c -o Flooding_Attack
Launching_Attack:
	gcc Launching_Attack.c -o Launching_Attack
run:
	gcc run.c -o run
clean:
	rm -f Check_Attack Flooding_Attack Launching_Attack run
